apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: dkfolkin/client
      context: client
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: dkfolkin/comments
      context: comments
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: dkfolkin/event-bus
      context: event-bus
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: dkfolkin/moderation
      context: moderation
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: dkfolkin/posts
      context: posts
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: dkfolkin/query
      context: query
      docker:
        dockerfile:  Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
